### ISSUE TITLE
Implement server tests

### ISSUE THREAD

**Issue by doriengr** [green-ecolution/green-ecolution#408]
- [ ] fileimport (Low priority because this is going to be moved to a plugin system)
- [ ] errorhandler
- [x] green-ecolution/green-ecolution#394 
- [x] green-ecolution/green-ecolution#401 
- [x] role (functionality not implemented yet - onhold)
- [x] green-ecolution/green-ecolution#396 (only GetAllSensor currently implemented)
- [x] green-ecolution/green-ecolution#398
- [x] green-ecolution/green-ecolution#400 
- [x] green-ecolution/green-ecolution#397
- [x] green-ecolution/green-ecolution#393
