### ISSUE TITLE
Implement Sensor Service

### ISSUE THREAD

**Issue by choffmann** [green-ecolution/green-ecolution#438]
- [x] green-ecolution/green-ecolution#376
- [x] green-ecolution/green-ecolution#375
- [x] green-ecolution/green-ecolution#368
- [x] Implement interpretations for watering status for trees
- [x] Implement interpretations for watering status for tree cluster
- [x] green-ecolution/green-ecolution#370
- [x] green-ecolution/green-ecolution#369
