### ISSUE TITLE
Implement Tree Service

### ISSUE THREAD

**Issue by choffmann** [green-ecolution/green-ecolution#443]
Add logic to:
- [x] Get all trees
- [x] Get a tree by id
- [x] green-ecolution/green-ecolution#430
- [x] green-ecolution/green-ecolution#433
- [x] green-ecolution/green-ecolution#429
