### ISSUE TITLE
Implement Api interface

### ISSUE THREAD

**Issue by choffmann** [green-ecolution/green-ecolution#449]
Implement api interface

- [x] green-ecolution/green-ecolution#451 
- [x] green-ecolution/green-ecolution#453 
- [x] green-ecolution/green-ecolution#455 
- [x] green-ecolution/green-ecolution#459 
- [x] green-ecolution/green-ecolution#448
- [x] green-ecolution/green-ecolution#446 (on hold)
- [x] green-ecolution/green-ecolution#445 (on hold)
