### ISSUE TITLE
Implement repository tests

### ISSUE THREAD

**Issue by choffmann** [green-ecolution/green-ecolution#456]
- [x] flowerbed (onhold)
- [x] vehicle
- [x] image (onhold)
- [x] green-ecolution/green-ecolution#389
- [x] green-ecolution/green-ecolution#390 
- [x] green-ecolution/green-ecolution#391
- [x] green-ecolution/green-ecolution#392
