### ISSUE TITLE
Writing test

### ISSUE THREAD

**Issue by choffmann** [green-ecolution/green-ecolution#469]
The application needs to be tested

- [x] green-ecolution/green-ecolution#456 
- [x] green-ecolution/green-ecolution#409 
- [x] green-ecolution/green-ecolution#408
